# Generated by Django 3.0.3 on 2020-03-07 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contetnt',
            new_name='content',
        ),
    ]
